MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/workspace/pretrained/mambavision_tiny_1k.pth.tar'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'mambavision_tiny_TransReID'
  DROP_PATH: 0.5
  DROP_OUT: 0.0
  ATT_DROP_RATE: 0.0
  ID_LOSS_WEIGHT: 1.0
  TRIPLET_LOSS_WEIGHT: 1.0
  POOLING_TYPE: 'gem'
  SIE_CAMERA: False
  EMA:
    ENABLED: False
    DECAY: 0.998
  MAMBAVISION:
    SASF_STAGES: []
    GLOBAL_STAGES: [2, 3]
    USE_SFM: False
    USE_FINE_BRANCH: False
  OSNET_FUSION:
    ENABLED: True
    OSNET_TYPE: 'osnet_x1_0'
    PRETRAIN_PATH: ''
    FREEZE_OSNET: False
    OSNET_LOSS_WEIGHT: 0.5
    FUSED_LOSS_WEIGHT: 1.0

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PAM:
    ENABLED: False
  OSBBM:
    ENABLED: True
    PROB: 0.25
    NUM_BLOCKS: 8
    NUM_MIX_BLOCKS: 2
    GRAY_PROB: 0.5
    APPLY_TO: 'base'
    SCHEDULE: 'cycle'
    START_EPOCH: 21
    END_EPOCH: 120
    PERIOD_EPOCHS: 20
    ON_EPOCHS: 10

DATASETS:
  NAMES: ('occ_duke')
  ROOT_DIR: '/workspace/data'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  MAX_EPOCHS: 160
  BASE_LR: 0.00035
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  WARMUP_EPOCHS: 20
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 50
  EVAL_PERIOD: 20
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.05
  BIAS_LR_FACTOR: 1
  SEED: 42
  MARGIN: 0.3
  STAGE4_LR_FACTOR: 2.0
  SASF_LR_FACTOR: 1.0
  OSNET_LR_FACTOR: 1.0
  OSNET_FUSION_LR_FACTOR: 2.0
  CLIP_GRAD_NORM: 10.0
  RATR_ENABLED: False

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/OCC-Duke/mambavision_tiny_osnet_concat_osbbm-b64k4'
