MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/workspace/pretrained/mambavision_tiny_1k.pth.tar'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'mambavision_tiny_TransReID'
  STRIDE_SIZE: [12, 12]
  DROP_PATH: 0.5
  DROP_OUT: 0.0
  ATT_DROP_RATE: 0.0
  ID_LOSS_WEIGHT: 1.0
  TRIPLET_LOSS_WEIGHT: 1.0
  EMA:
    ENABLED: False
    DECAY: 0.998
  POOLING_TYPE: 'gem'
  MAMBAVISION:
    SASF_STAGES: []
    GLOBAL_STAGES: [2, 3]
    USE_SFM: False
    SFM_POOLING_TYPE: 'gem'
    SFM_DEPTHS: [1, 2, 3]
    SFM_DROP_PATH: 0.05
  BPBREID:
    ENABLED: True
    PARTS_NUM: 5
    DIM_REDUCE: 512
    HIGH_RESOLUTION_ENABLED: True
    HIGH_RESOLUTION_DIM: 256
    POOLING_FEATURE_SOURCE: 'semantic'
    ANCHOR_ENABLED: True
    ANCHOR_ID_WEIGHT: 1.0
    ANCHOR_TRIPLET_WEIGHT: 1.0
    ANCHOR_DISTANCE_WEIGHT: 0.5
    SHARED_PARTS_ID_CLASSIFIER: False
    TRAINING_BINARY_VISIBILITY: True
    TESTING_BINARY_VISIBILITY: True
    MASK_FILTERING_TRAINING: False
    MASK_FILTERING_TESTING: True
    TEST_USE_TARGET_SEGMENTATION: 'none'
    TEST_EMBEDDINGS: ['bn_foreg', 'parts']
    MASKS_BASE_DIR: 'masks'
    MASKS_DIR: 'pifpaf_maskrcnn_filtering'
    MASKS_SUFFIX: '.npy'
    MASKS_SOURCE_CHANNELS: 36
    MASKS_PREPROCESS: 'five_v'
    MASKS_SOFTMAX_WEIGHT: 15.0
    MASKS_BACKGROUND_STRATEGY: 'threshold'
    MASKS_FILTERING_THRESHOLD: 0.5
    MASK_SCALE: 4
    GLOBAL_ID_WEIGHT: 1.0
    GLOBAL_TRIPLET_WEIGHT: 0.0
    FOREGROUND_ID_WEIGHT: 1.0
    FOREGROUND_TRIPLET_WEIGHT: 1.0
    CONCAT_PARTS_ID_WEIGHT: 1.0
    CONCAT_PARTS_TRIPLET_WEIGHT: 0.0
    PARTS_ID_WEIGHT: 0.0
    PARTS_TRIPLET_WEIGHT: 1.0
    ATTENTION_LOSS_WEIGHT: 0.35
INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATASETS:
  NAMES: ('dukemtmc')
  ROOT_DIR: '/workspace/data'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  MAX_EPOCHS: 160
  BASE_LR: 0.00035
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  WARMUP_EPOCHS: 20
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 50
  EVAL_PERIOD: 20
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.05
  BIAS_LR_FACTOR: 1
  SEED: 42
  MARGIN: 0.3
  STAGE4_LR_FACTOR: 2.0
  SASF_LR_FACTOR: 3.0
  CLIP_GRAD_NORM: 10.0
  SFM_LAMBDA: 1.0
  SFM_LAMBDA_AUX: 0.3
  SFM_LR_FACTOR: 2.0
  BPBREID_LR_FACTOR: 2.0
  RATR_ENABLED: False
  RATR_LAMBDA: 1.0
  RATR_TAU: 0.1
TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/Duke/MambaVision-BPBreID-PifPaf-Semantic-BPGlobalGeM-GeMAnchor-256x128'
